### ISSUE TITLE
Add full backup frequency to the documentation

### ISSUE THREAD

**Issue by cruizer** [cruizer/dup-composer#21]
Reminder example:
```yaml
backup_groups:
  my_backup_group:
    full_backup_frequency: 1M
    ...
  ...
```
